### ISSUE TITLE
[Feature Request] Add json serialization

### ISSUE THREAD

**Issue by gadfly361** [marcelgarus/data_classes#2]
Thanks for sharing this library! I have definitely been wanting to use something like this.

Is it possible to add json serialization to the generated data class?  

My specific use-case is that I'd like to use [json_serializable](https://pub.dev/packages/json_serializable). To use it, I'd need to add some boilerplate (`toJson` and `fromJson`) to the generated data class; however, the generated data class can't be edited by hand.

**Comment by marcelgarus** [comment]
Hmm good question. I guess we could try to add a meta-anmotation like
`@Annotation(JsonSerializable)` to the mutable class to then add the actual annotation `@JsonAnnotation` to the generated class.
But I'm not even sure you can add annotations in generated files...
This issue doesn't have the highest priority right now, so it'll take some time until I evaluate/implement this. Of course you're welcome to contribute to the project, if you want to!
In the meantime, you can of course add `@JsonSerializable` to the mutable class and use `User.toMutable().toJson()` and `User.fromMutable(MutableUser.fromJson(json))` although of course, this is more boilerplate.
Also, take into consideration that static extension methods are actively being worked on by the Dart team right now, so soon you'll be able to define `User.toJson() => this.toMutable().toJson()` in the original file.

**Comment by gadfly361** [comment]
@marcelgarus Thanks for the detailed response! I am going to close this in favor of tracking [#4](https://github.com/marcelgarus/data_classes/issues/4)
