### ISSUE TITLE
Generated code is not compilable 

### ISSUE THREAD

**Issue by wiradikusuma** [marcelgarus/data_classes#5]
I have this class:

	part 'ReminderArgs.g.dart';

	@DataClass()
	class ReminderArgs {
		@nullable String assetId;
		@nullable Reminder reminder;
		bool showAsset = false;
	}

and this is what data_classes generates:

    // GENERATED CODE - DO NOT MODIFY BY HAND

    part of 'ReminderArgs.dart';

    // **************************************************************************
    // DataClassGenerator
    // **************************************************************************

    /// This class is the immutable pendant of the MutablerArgs class.
    @immutable
    class rArgs {
      final String assetId;
      final Reminder reminder;
      final bool showAsset;

      /// Default constructor that creates a rArgs.
      const rArgs({
        this.assetId,
        this.reminder,
        @required this.showAsset,
      }) : assert(showAsset != null);

      /// Creates a rArgs from a MutablerArgs.
      factory rArgs.fromMutable(MutablerArgs mutable) {
        return rArgs(
          assetId: mutable.assetId,
          reminder: mutable.reminder,
          showAsset: mutable.showAsset,
        );
      }

      /// Turns this rArgs into a MutablerArgs.
      MutablerArgs toMutable() {
        return MutablerArgs()
          ..assetId = assetId
          ..reminder = reminder
          ..showAsset = showAsset;
      }

      /// Checks if this rArgs is equal to the other one.
      bool operator ==(Object other) {
        return other is rArgs &&
            assetId == other.assetId &&
            reminder == other.reminder &&
            showAsset == other.showAsset;
      }

      int get hashCode => hashList([
            assetId,
            reminder,
            showAsset,
          ]);

      rArgs copyWith({
        String assetId,
        Reminder reminder,
        bool showAsset,
      }) {
        return rArgs(
          assetId: assetId ?? this.assetId,
          reminder: reminder ?? this.reminder,
          showAsset: showAsset ?? this.showAsset,
        );
      }

      String toString() {
        return 'rArgs\n'
            '  assetId: $assetId\n'
            '  reminder: $reminder\n'
            '  showAsset: $showAsset\n'
            ')';
      }
    }

pubspec.yaml:

  dependencies:
    data_classes: ^1.1.0
    flutter:
      sdk: flutter
    flutter_localizations:
      sdk: flutter
    flutter_mobx: ^0.3.1+1
    mobx: ^0.3.7
    package_info: ^0.4.0+6

  dev_dependencies:
    build_runner: ^1.6.7
    data_classes_generator: ^1.1.0
    mobx_codegen: ^0.3.6

**Comment by marcelgarus** [comment]
Here's how to fix it: Classes marked with `@DataClass()` (or `@GenerateDataClassFor()` since the newest version 2 of this package) should start with `Mutable`, so in your case `MutableReminderArgs`.

The code generator should throw an error if that's not the case, I'll look into it.

**Comment by marcelgarus** [comment]
Seems like assertions are not executed during code generation. I'll fix that.

**Comment by marcelgarus** [comment]
Fixed in the newest version, 2.0.1, of the package.
